namespace ADB_Tool_Automation_Post_FB.Core.Vision
{
    public enum TemplateId
    {
        WorldMapAnchor,
        ContinentMapTitle,
        ResourceSearchPanelAnchor,
        SearchButtonEnabled,
        ResourceTabSelected,
        ResourceTabUnselected,
        ResourceIronSelected,
        ResourceIronUnselected,
        LevelMinusButton,
        LevelPlusButton,
        LevelValue7,
        UnoccupiedFilterChecked,
        UnoccupiedFilterUnchecked,
        CheckboxChecked,
        CheckboxUnchecked,
        ResourceNotFoundToast,
        ResourceNotFoundToastAnchor,
        ResourceNotFoundToastActionAnchor,
        ResourcePopup,
        GatherButton,
        TeamPanel,
        TeamFree,
        TeamBusy,
        TeamSelected,
        NetworkError,
        ReconnectButton
    }
}
